[2018-04-11 20:07:20] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\symfony_4\var\cache\de~): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\symfony_4\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":184,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\symfony_4\\\\vendor\\\\symfony\\\\framework-bundle\\\\Command\\\\CacheClearCommand.php\",\"line\":84,\"function\":\"remove\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-11 20:07:20] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\symfony_4\var\cache\de_): No such file or directory [] []
[2018-04-11 20:07:22] php.DEBUG: Warning: include(C:\Users\micha\Desktop\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php): failed to open stream: No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"function\":\"include\"},{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":125,\"function\":\"initializeContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-11 20:07:22] php.DEBUG: Warning: include(): Failed opening 'C:\Users\micha\Desktop\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2018-04-11 20:07:24] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\symfony_4\var\cache\de_/ContainerSKgz3u5.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":707,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":535,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-16 17:44:42] php.DEBUG: Warning: unlink(C:\xampp\htdocs\projekt pokazowy\symfony_4\var\cache\de~): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":184,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\framework-bundle\\\\Command\\\\CacheClearCommand.php\",\"line\":84,\"function\":\"remove\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-16 17:44:42] php.DEBUG: Warning: unlink(C:\xampp\htdocs\projekt pokazowy\symfony_4\var\cache\de_): No such file or directory [] []
[2018-04-16 17:44:44] php.DEBUG: Warning: include(C:\xampp\htdocs\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php): failed to open stream: No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"function\":\"include\"},{\"file\":\"C:\\\\xampp\\\\htdocs\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":125,\"function\":\"initializeContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-16 17:44:44] php.DEBUG: Warning: include(): Failed opening 'C:\xampp\htdocs\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2018-04-16 17:44:52] php.DEBUG: Warning: unlink(C:\xampp\htdocs\projekt pokazowy\symfony_4\var\cache\de_/ContainerJwn1Bvt.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":707,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":535,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-16 18:00:12] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-16 18:00:31] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\xampp\\\\htdocs\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\xampp\\\\htdocs\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-16 18:00:41] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"70b47c","_route":"_wdt"},"request_uri":"http://localhost:8000/_wdt/70b47c","method":"GET"} []
[2018-04-16 18:00:43] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://localhost:8000/")" at C:\xampp\htdocs\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\EventListener\RouterListener.php line 144 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:8000/\") at C:\\xampp\\htdocs\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:144, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\projekt pokazowy\\symfony_4\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:114)"} []
[2018-04-20 23:11:27] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:11:40] php.DEBUG: Warning: filemtime(): stat failed for C:\xampp\htdocs\projekt pokazowy\symfony_4\config\routes\annotations.yaml {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\config\\\\Resource\\\\FileResource.php\",\"line\":63,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\config\\\\Resource\\\\SelfCheckingResourceChecker.php\",\"line\":34,\"function\":\"isFresh\",\"class\":\"Symfony\\\\Component\\\\Config\\\\Resource\\\\FileResource\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:11:42] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"71cd57","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/71cd57","method":"GET"} []
[2018-04-20 23:11:43] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://127.0.0.1:8000/")" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\EventListener\RouterListener.php line 144 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://127.0.0.1:8000/\") at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:144, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:114)"} []
[2018-04-20 23:15:15] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de~): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":184,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\framework-bundle\\\\Command\\\\CacheClearCommand.php\",\"line\":84,\"function\":\"remove\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:15:15] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_): No such file or directory [] []
[2018-04-20 23:15:16] php.DEBUG: Warning: include(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php): failed to open stream: No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"function\":\"include\"},{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":125,\"function\":\"initializeContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:15:16] php.DEBUG: Warning: include(): Failed opening 'C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2018-04-20 23:15:18] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/Container1ieDwz6.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":707,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":535,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:23:50] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:23:54] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-20 23:23:54] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-20 23:23:55] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"e5bd54","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/e5bd54","method":"GET"} []
[2018-04-20 23:27:16] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:27:57] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de~): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":184,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\framework-bundle\\\\Command\\\\CacheClearCommand.php\",\"line\":84,\"function\":\"remove\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:27:57] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_): No such file or directory [] []
[2018-04-20 23:27:59] php.DEBUG: Warning: include(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php): failed to open stream: No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"function\":\"include\"},{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":125,\"function\":\"initializeContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:27:59] php.DEBUG: Warning: include(): Failed opening 'C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2018-04-20 23:28:01] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/ContainerJp44lvs.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":707,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":535,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:29:20] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de~): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":184,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\framework-bundle\\\\Command\\\\CacheClearCommand.php\",\"line\":84,\"function\":\"remove\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:29:21] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_): No such file or directory [] []
[2018-04-20 23:29:22] php.DEBUG: Warning: include(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php): failed to open stream: No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"function\":\"include\"},{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":125,\"function\":\"initializeContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:29:22] php.DEBUG: Warning: include(): Failed opening 'C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2018-04-20 23:29:24] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/ContainerJp44lvs.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":707,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":535,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:31:32] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de~): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":184,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\framework-bundle\\\\Command\\\\CacheClearCommand.php\",\"line\":84,\"function\":\"remove\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:31:33] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_): No such file or directory [] []
[2018-04-20 23:31:34] php.DEBUG: Warning: include(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php): failed to open stream: No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"function\":\"include\"},{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":125,\"function\":\"initializeContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:31:34] php.DEBUG: Warning: include(): Failed opening 'C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2018-04-20 23:31:36] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/ContainerVQqzBe0.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":707,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":535,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-20 23:38:51] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)"} []
[2018-04-20 23:38:51] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-20 23:40:06] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)"} []
[2018-04-20 23:40:06] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-20 23:42:15] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)"} []
[2018-04-20 23:42:15] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-20 23:42:30] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)"} []
[2018-04-20 23:42:30] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-20 23:44:54] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "Connection does not contain a 'path' or 'dbname' parameter and cannot be dropped." {"error":"[object] (InvalidArgumentException(code: 0): Connection does not contain a 'path' or 'dbname' parameter and cannot be dropped. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\doctrine-bundle\\Command\\CreateDatabaseDoctrineCommand.php:93)","command":"doctrine:database:create","message":"Connection does not contain a 'path' or 'dbname' parameter and cannot be dropped."} []
[2018-04-20 23:44:54] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-20 23:49:23] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "Connection does not contain a 'path' or 'dbname' parameter and cannot be dropped." {"error":"[object] (InvalidArgumentException(code: 0): Connection does not contain a 'path' or 'dbname' parameter and cannot be dropped. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\doctrine-bundle\\Command\\CreateDatabaseDoctrineCommand.php:93)","command":"doctrine:database:create","message":"Connection does not contain a 'path' or 'dbname' parameter and cannot be dropped."} []
[2018-04-20 23:49:23] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-20 23:49:47] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "Connection does not contain a 'path' or 'dbname' parameter and cannot be dropped." {"error":"[object] (InvalidArgumentException(code: 0): Connection does not contain a 'path' or 'dbname' parameter and cannot be dropped. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\doctrine-bundle\\Command\\CreateDatabaseDoctrineCommand.php:93)","command":"doctrine:database:create","message":"Connection does not contain a 'path' or 'dbname' parameter and cannot be dropped."} []
[2018-04-20 23:49:47] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-20 23:53:46] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)"} []
[2018-04-20 23:53:46] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-20 23:56:04] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)"} []
[2018-04-20 23:56:04] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-20 23:57:30] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)"} []
[2018-04-20 23:57:30] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-20 23:57:54] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)"} []
[2018-04-20 23:57:54] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-20 23:58:18] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)"} []
[2018-04-20 23:58:18] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-20 23:58:35] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-21 00:00:17] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-21 00:00:17] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-21 00:00:17] php.CRITICAL: Class 'App\Controller\PDO' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'App\\Controller\\PDO' not found at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\src\\Controller\\ItemsController.php:26)"} []
[2018-04-21 00:00:20] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "PDO" from namespace "App\Controller". Did you forget a "use" statement for another namespace?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\src\Controller\ItemsController.php line 26 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"PDO\" from namespace \"App\\Controller\".\nDid you forget a \"use\" statement for another namespace? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\src\\Controller\\ItemsController.php:26)"} []
[2018-04-21 00:00:21] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"be1b0b","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/be1b0b","method":"GET"} []
[2018-04-21 00:03:08] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)"} []
[2018-04-21 00:03:08] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-21 00:04:05] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)"} []
[2018-04-21 00:04:05] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-21 00:04:33] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)"} []
[2018-04-21 00:04:33] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-21 00:06:59] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de~): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":184,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\framework-bundle\\\\Command\\\\CacheClearCommand.php\",\"line\":84,\"function\":\"remove\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-21 00:07:00] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_): No such file or directory [] []
[2018-04-21 00:07:02] php.DEBUG: Warning: include(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php): failed to open stream: No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"function\":\"include\"},{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":125,\"function\":\"initializeContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-21 00:07:02] php.DEBUG: Warning: include(): Failed opening 'C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2018-04-21 00:07:04] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/ContainerVWnxkn0.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":707,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":535,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-21 00:14:27] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)" {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)"} []
[2018-04-21 00:14:27] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-21 00:14:56] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2018-04-21 00:20:57] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-21 00:21:09] request.INFO: Matched route "app_items_index". {"route":"app_items_index","route_parameters":{"_controller":"App\\Controller\\ItemsController::indexAction","_route":"app_items_index"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-21 00:21:09] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-21 00:21:10] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-21 00:21:10] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT * FROM users':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shop.users' doesn't exist" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 61 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM users':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'shop.users' doesn't exist at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:61, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shop.users' doesn't exist at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:109, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shop.users' doesn't exist at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:107)"} []
[2018-04-21 00:21:10] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"aec6e9","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/aec6e9","method":"GET"} []
[2018-04-21 00:22:19] request.INFO: Matched route "app_items_index". {"route":"app_items_index","route_parameters":{"_controller":"App\\Controller\\ItemsController::indexAction","_route":"app_items_index"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-21 00:22:19] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-21 00:22:19] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-21 00:22:19] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-21 00:22:19] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"935909","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/935909","method":"GET"} []
[2018-04-21 00:22:21] request.INFO: Matched route "app_items_index". {"route":"app_items_index","route_parameters":{"_controller":"App\\Controller\\ItemsController::indexAction","_route":"app_items_index"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-21 00:22:21] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-21 00:22:21] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-21 00:22:21] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-21 00:22:21] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"a613b6","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/a613b6","method":"GET"} []
[2018-04-21 00:22:48] request.INFO: Matched route "app_items_index". {"route":"app_items_index","route_parameters":{"_controller":"App\\Controller\\ItemsController::indexAction","_route":"app_items_index"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-21 00:22:48] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-21 00:22:48] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-21 00:22:48] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-21 00:22:48] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"527855","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/527855","method":"GET"} []
[2018-04-27 21:52:41] console.DEBUG: Command "make:entity" exited with code "1" {"command":"make:entity","code":1} []
[2018-04-27 21:54:57] console.ERROR: Error thrown while running command "make:migration". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it. " {"error":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.\r\n at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.\r\n at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 2002): SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.\r\n at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)","command":"make:migration","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.\r\n"} []
[2018-04-27 21:54:57] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2018-04-27 21:55:27] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2018-04-27 21:55:27] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'shop' AND TABLE_NAME = 'users' [] []
[2018-04-27 21:55:28] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'users' */ WHERE k.table_name = 'users' AND k.table_schema = 'shop' /*!50116 AND c.constraint_schema = 'shop' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2018-04-27 21:55:28] doctrine.DEBUG: SELECT TABLE_NAME AS `Table`, NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, SEQ_IN_INDEX AS Seq_in_index, COLUMN_NAME AS Column_Name, COLLATION AS Collation, CARDINALITY AS Cardinality, SUB_PART AS Sub_Part, PACKED AS Packed, NULLABLE AS `Null`, INDEX_TYPE AS Index_Type, COMMENT AS Comment FROM information_schema.STATISTICS WHERE TABLE_NAME = 'users' AND TABLE_SCHEMA = 'shop' [] []
[2018-04-27 21:55:28] console.ERROR: Error thrown while running command "make:migration". Message: "The helper "entityManager" is not defined." {"error":"[object] (Symfony\\Component\\Console\\Exception\\InvalidArgumentException(code: 0): The helper \"entityManager\" is not defined. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\console\\Helper\\HelperSet.php:80)","command":"make:migration","message":"The helper \"entityManager\" is not defined."} []
[2018-04-27 21:55:28] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2018-04-27 21:55:41] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2018-04-27 21:55:41] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'shop' AND TABLE_NAME = 'users' [] []
[2018-04-27 21:55:41] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'users' */ WHERE k.table_name = 'users' AND k.table_schema = 'shop' /*!50116 AND c.constraint_schema = 'shop' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2018-04-27 21:55:41] doctrine.DEBUG: SELECT TABLE_NAME AS `Table`, NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, SEQ_IN_INDEX AS Seq_in_index, COLUMN_NAME AS Column_Name, COLLATION AS Collation, CARDINALITY AS Cardinality, SUB_PART AS Sub_Part, PACKED AS Packed, NULLABLE AS `Null`, INDEX_TYPE AS Index_Type, COMMENT AS Comment FROM information_schema.STATISTICS WHERE TABLE_NAME = 'users' AND TABLE_SCHEMA = 'shop' [] []
[2018-04-27 21:55:41] console.ERROR: Error thrown while running command "make:migration". Message: "The helper "entityManager" is not defined." {"error":"[object] (Symfony\\Component\\Console\\Exception\\InvalidArgumentException(code: 0): The helper \"entityManager\" is not defined. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\console\\Helper\\HelperSet.php:80)","command":"make:migration","message":"The helper \"entityManager\" is not defined."} []
[2018-04-27 21:55:41] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2018-04-27 21:56:35] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2018-04-27 21:56:35] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'shop' AND TABLE_NAME = 'users' [] []
[2018-04-27 21:56:35] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'users' */ WHERE k.table_name = 'users' AND k.table_schema = 'shop' /*!50116 AND c.constraint_schema = 'shop' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2018-04-27 21:56:35] doctrine.DEBUG: SELECT TABLE_NAME AS `Table`, NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, SEQ_IN_INDEX AS Seq_in_index, COLUMN_NAME AS Column_Name, COLLATION AS Collation, CARDINALITY AS Cardinality, SUB_PART AS Sub_Part, PACKED AS Packed, NULLABLE AS `Null`, INDEX_TYPE AS Index_Type, COMMENT AS Comment FROM information_schema.STATISTICS WHERE TABLE_NAME = 'users' AND TABLE_SCHEMA = 'shop' [] []
[2018-04-27 21:56:35] console.ERROR: Error thrown while running command "make:migration". Message: "The helper "entityManager" is not defined." {"error":"[object] (Symfony\\Component\\Console\\Exception\\InvalidArgumentException(code: 0): The helper \"entityManager\" is not defined. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\console\\Helper\\HelperSet.php:80)","command":"make:migration","message":"The helper \"entityManager\" is not defined."} []
[2018-04-27 21:56:35] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2018-04-27 21:56:47] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2018-04-27 21:56:47] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'shop' AND TABLE_NAME = 'users' [] []
[2018-04-27 21:56:47] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'users' */ WHERE k.table_name = 'users' AND k.table_schema = 'shop' /*!50116 AND c.constraint_schema = 'shop' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2018-04-27 21:56:47] doctrine.DEBUG: SELECT TABLE_NAME AS `Table`, NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, SEQ_IN_INDEX AS Seq_in_index, COLUMN_NAME AS Column_Name, COLLATION AS Collation, CARDINALITY AS Cardinality, SUB_PART AS Sub_Part, PACKED AS Packed, NULLABLE AS `Null`, INDEX_TYPE AS Index_Type, COMMENT AS Comment FROM information_schema.STATISTICS WHERE TABLE_NAME = 'users' AND TABLE_SCHEMA = 'shop' [] []
[2018-04-27 21:56:47] console.ERROR: Error thrown while running command "make:migration". Message: "The helper "entityManager" is not defined." {"error":"[object] (Symfony\\Component\\Console\\Exception\\InvalidArgumentException(code: 0): The helper \"entityManager\" is not defined. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\console\\Helper\\HelperSet.php:80)","command":"make:migration","message":"The helper \"entityManager\" is not defined."} []
[2018-04-27 21:56:47] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2018-04-27 22:01:22] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de~): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":184,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\framework-bundle\\\\Command\\\\CacheClearCommand.php\",\"line\":84,\"function\":\"remove\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-27 22:01:23] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_): No such file or directory [] []
[2018-04-27 22:01:24] php.DEBUG: Warning: include(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php): failed to open stream: No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"function\":\"include\"},{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":125,\"function\":\"initializeContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-27 22:01:24] php.DEBUG: Warning: include(): Failed opening 'C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2018-04-27 22:01:25] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/ContainerNDrqfIj.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":707,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":535,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-27 22:01:54] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2018-04-27 22:01:54] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'shop' AND TABLE_NAME = 'users' [] []
[2018-04-27 22:01:55] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'users' */ WHERE k.table_name = 'users' AND k.table_schema = 'shop' /*!50116 AND c.constraint_schema = 'shop' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2018-04-27 22:01:55] doctrine.DEBUG: SELECT TABLE_NAME AS `Table`, NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, SEQ_IN_INDEX AS Seq_in_index, COLUMN_NAME AS Column_Name, COLLATION AS Collation, CARDINALITY AS Cardinality, SUB_PART AS Sub_Part, PACKED AS Packed, NULLABLE AS `Null`, INDEX_TYPE AS Index_Type, COMMENT AS Comment FROM information_schema.STATISTICS WHERE TABLE_NAME = 'users' AND TABLE_SCHEMA = 'shop' [] []
[2018-04-27 22:01:55] console.ERROR: Error thrown while running command "make:migration". Message: "The helper "entityManager" is not defined." {"error":"[object] (Symfony\\Component\\Console\\Exception\\InvalidArgumentException(code: 0): The helper \"entityManager\" is not defined. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\console\\Helper\\HelperSet.php:80)","command":"make:migration","message":"The helper \"entityManager\" is not defined."} []
[2018-04-27 22:01:55] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2018-04-27 22:04:25] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de~): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":184,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\framework-bundle\\\\Command\\\\CacheClearCommand.php\",\"line\":84,\"function\":\"remove\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-27 22:04:25] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_): No such file or directory [] []
[2018-04-27 22:04:26] php.DEBUG: Warning: include(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php): failed to open stream: No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"function\":\"include\"},{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":125,\"function\":\"initializeContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-27 22:04:26] php.DEBUG: Warning: include(): Failed opening 'C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2018-04-27 22:04:28] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/ContainerNDrqfIj.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":707,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":535,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-27 22:09:37] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2018-04-27 22:09:37] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'shop' AND TABLE_NAME = 'users' [] []
[2018-04-27 22:09:37] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'users' */ WHERE k.table_name = 'users' AND k.table_schema = 'shop' /*!50116 AND c.constraint_schema = 'shop' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2018-04-27 22:09:37] doctrine.DEBUG: SELECT TABLE_NAME AS `Table`, NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, SEQ_IN_INDEX AS Seq_in_index, COLUMN_NAME AS Column_Name, COLLATION AS Collation, CARDINALITY AS Cardinality, SUB_PART AS Sub_Part, PACKED AS Packed, NULLABLE AS `Null`, INDEX_TYPE AS Index_Type, COMMENT AS Comment FROM information_schema.STATISTICS WHERE TABLE_NAME = 'users' AND TABLE_SCHEMA = 'shop' [] []
[2018-04-27 22:09:37] console.ERROR: Error thrown while running command "make:migration". Message: "The helper "entityManager" is not defined." {"error":"[object] (Symfony\\Component\\Console\\Exception\\InvalidArgumentException(code: 0): The helper \"entityManager\" is not defined. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\console\\Helper\\HelperSet.php:80)","command":"make:migration","message":"The helper \"entityManager\" is not defined."} []
[2018-04-27 22:09:37] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2018-04-27 22:10:43] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2018-04-27 22:10:43] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'shop' AND TABLE_NAME = 'users' [] []
[2018-04-27 22:10:43] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'users' */ WHERE k.table_name = 'users' AND k.table_schema = 'shop' /*!50116 AND c.constraint_schema = 'shop' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2018-04-27 22:10:43] doctrine.DEBUG: SELECT TABLE_NAME AS `Table`, NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, SEQ_IN_INDEX AS Seq_in_index, COLUMN_NAME AS Column_Name, COLLATION AS Collation, CARDINALITY AS Cardinality, SUB_PART AS Sub_Part, PACKED AS Packed, NULLABLE AS `Null`, INDEX_TYPE AS Index_Type, COMMENT AS Comment FROM information_schema.STATISTICS WHERE TABLE_NAME = 'users' AND TABLE_SCHEMA = 'shop' [] []
[2018-04-27 22:10:44] console.ERROR: Error thrown while running command "make:migration". Message: "The helper "entityManager" is not defined." {"error":"[object] (Symfony\\Component\\Console\\Exception\\InvalidArgumentException(code: 0): The helper \"entityManager\" is not defined. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\console\\Helper\\HelperSet.php:80)","command":"make:migration","message":"The helper \"entityManager\" is not defined."} []
[2018-04-27 22:10:44] console.DEBUG: Command "make:migration" exited with code "1" {"command":"make:migration","code":1} []
[2018-04-29 18:20:15] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-29 18:31:21] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"96eed4","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/96eed4","method":"GET"} []
[2018-04-29 18:31:23] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://127.0.0.1:8000/")" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\EventListener\RouterListener.php line 144 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://127.0.0.1:8000/\") at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:144, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:119)"} []
[2018-04-29 18:31:54] request.INFO: Matched route "app_items_index". {"route":"app_items_index","route_parameters":{"_controller":"App\\Controller\\ItemsController::indexAction","_route":"app_items_index"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:31:54] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:31:56] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it. " at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.\r\n at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.\r\n at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:50, PDOException(code: 2002): SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.\r\n at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:46)"} []
[2018-04-29 18:31:57] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"ea1d54","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/ea1d54","method":"GET"} []
[2018-04-29 18:32:22] request.INFO: Matched route "app_items_index". {"route":"app_items_index","route_parameters":{"_controller":"App\\Controller\\ItemsController::indexAction","_route":"app_items_index"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:32:22] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:32:22] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 18:32:22] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-29 18:32:23] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"f3dc12","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/f3dc12","method":"GET"} []
[2018-04-29 18:32:47] request.INFO: Matched route "app_items_index". {"route":"app_items_index","route_parameters":{"_controller":"App\\Controller\\ItemsController::indexAction","_route":"app_items_index"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:32:47] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:32:47] doctrine.DEBUG: SELECT * FROM items [] []
[2018-04-29 18:32:47] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT * FROM items':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shop.items' doesn't exist" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 61 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM items':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'shop.items' doesn't exist at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:61, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shop.items' doesn't exist at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:109, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shop.items' doesn't exist at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:107)"} []
[2018-04-29 18:32:47] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"9ff32b","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/9ff32b","method":"GET"} []
[2018-04-29 18:33:38] request.INFO: Matched route "app_items_index". {"route":"app_items_index","route_parameters":{"_controller":"App\\Controller\\ItemsController::indexAction","_route":"app_items_index"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:33:38] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:33:38] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 18:33:38] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-29 18:33:39] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"575ec1","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/575ec1","method":"GET"} []
[2018-04-29 18:34:17] request.INFO: Matched route "app_items_index". {"route":"app_items_index","route_parameters":{"_controller":"App\\Controller\\ItemsController::indexAction","_route":"app_items_index"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:34:17] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:34:17] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 18:34:17] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (Array(0 => Array(id => 1, name => gosc)) given)." at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (Array(0 => Array(id => 1, name => gosc)) given). at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-29 18:34:17] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"4ed15f","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/4ed15f","method":"GET"} []
[2018-04-29 18:36:52] request.INFO: Matched route "app_items_index". {"route":"app_items_index","route_parameters":{"_controller":"App\\Controller\\ItemsController::indexAction","_route":"app_items_index"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:36:52] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:36:52] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 18:36:52] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (Array(0 => Array(id => 1, name => gosc)) given)." at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (Array(0 => Array(id => 1, name => gosc)) given). at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-29 18:36:52] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"008929","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/008929","method":"GET"} []
[2018-04-29 18:38:03] request.INFO: Matched route "app_items_index". {"route":"app_items_index","route_parameters":{"_controller":"App\\Controller\\ItemsController::indexAction","_route":"app_items_index"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:38:04] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:38:04] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 18:38:04] php.CRITICAL: Call to undefined function App\Controller\response() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function App\\Controller\\response() at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\src\\Controller\\ItemsController.php:19)"} []
[2018-04-29 18:38:04] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "response" from namespace "App\Controller"." at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\src\Controller\ItemsController.php line 19 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"response\" from namespace \"App\\Controller\". at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\src\\Controller\\ItemsController.php:19)"} []
[2018-04-29 18:38:04] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"026153","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/026153","method":"GET"} []
[2018-04-29 18:40:28] request.INFO: Matched route "app_items_index". {"route":"app_items_index","route_parameters":{"_controller":"App\\Controller\\ItemsController::indexAction","_route":"app_items_index"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:40:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:40:28] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 18:40:28] php.CRITICAL: Call to undefined function App\Controller\Response() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function App\\Controller\\Response() at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\src\\Controller\\ItemsController.php:19)"} []
[2018-04-29 18:40:28] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "Response" from namespace "App\Controller"." at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\src\Controller\ItemsController.php line 19 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"Response\" from namespace \"App\\Controller\". at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\src\\Controller\\ItemsController.php:19)"} []
[2018-04-29 18:40:28] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"b55622","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/b55622","method":"GET"} []
[2018-04-29 18:44:04] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de~): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\filesystem\\\\Filesystem.php\",\"line\":184,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\framework-bundle\\\\Command\\\\CacheClearCommand.php\",\"line\":84,\"function\":\"remove\",\"class\":\"Symfony\\\\Component\\\\Filesystem\\\\Filesystem\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-29 18:44:05] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_): No such file or directory [] []
[2018-04-29 18:44:06] php.DEBUG: Warning: include(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php): failed to open stream: No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":526,\"function\":\"include\"},{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":125,\"function\":\"initializeContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-29 18:44:06] php.DEBUG: Warning: include(): Failed opening 'C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/srcDevDebugProjectContainer.php' for inclusion (include_path='C:\xampp\php\PEAR') [] []
[2018-04-29 18:44:08] php.DEBUG: Warning: unlink(C:\Users\micha\Desktop\projekt pokazowy\symfony_4\var\cache\de_/ContainerNDrqfIj.legacy): No such file or directory {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":707,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\http-kernel\\\\Kernel.php\",\"line\":535,\"function\":\"dumpContainer\",\"class\":\"Symfony\\\\Component\\\\HttpKernel\\\\Kernel\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-29 18:46:36] php.DEBUG: Warning: fsockopen(): unable to connect to 127.0.0.1:8000 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\SilencedErrorContext: {\"severity\":2,\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":123,\"trace\":[{\"file\":\"C:\\\\Users\\\\micha\\\\Desktop\\\\projekt pokazowy\\\\symfony_4\\\\vendor\\\\symfony\\\\web-server-bundle\\\\WebServerConfig.php\",\"line\":54,\"function\":\"findBestPort\",\"class\":\"Symfony\\\\Bundle\\\\WebServerBundle\\\\WebServerConfig\",\"type\":\"->\"}],\"count\":1})"} []
[2018-04-29 18:54:20] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:54:20] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:54:20] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-29 18:54:20] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"771154","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/771154","method":"GET"} []
[2018-04-29 18:55:25] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:55:25] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:55:25] php.CRITICAL: Class 'App\Controller\JsonResponse' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'App\\Controller\\JsonResponse' not found at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\src\\Controller\\ItemsController.php:17)"} []
[2018-04-29 18:55:28] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "JsonResponse" from namespace "App\Controller". Did you forget a "use" statement for "Symfony\Component\HttpFoundation\JsonResponse"?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\src\Controller\ItemsController.php line 17 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"JsonResponse\" from namespace \"App\\Controller\".\nDid you forget a \"use\" statement for \"Symfony\\Component\\HttpFoundation\\JsonResponse\"? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\src\\Controller\\ItemsController.php:17)"} []
[2018-04-29 18:55:29] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"d009bf","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/d009bf","method":"GET"} []
[2018-04-29 18:55:54] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\FileLoaderLoadException: "[Semantical Error] The annotation "@Route" in method App\Controller\ItemsController::items() was never imported. Did you maybe forget to add a "use" statement for this annotation? in C:\Users\micha\Desktop\projekt pokazowy\symfony_4\config/routes\../../src/Controller/ (which is being imported from "C:\Users\micha\Desktop\projekt pokazowy\symfony_4\config/routes/annotations.yaml"). Make sure annotations are installed and enabled." at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\config\Loader\FileLoader.php line 168 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\config\\Loader\\FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:54)"} []
[2018-04-29 18:55:54] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("[Semantical Error] The annotation "@Route" in method App\Controller\ItemsController::items() was never imported. Did you maybe forget to add a "use" statement for this annotation? in C:\Users\micha\Desktop\projekt pokazowy\symfony_4\config/routes\../../src/Controller/ (which is being imported from "C:\Users\micha\Desktop\projekt pokazowy\symfony_4\config/routes/annotations.yaml"). Make sure annotations are installed and enabled."). at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\config\\Loader\\FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:54)"} []
[2018-04-29 18:55:54] php.CRITICAL: Uncaught Exception: An exception has been thrown during the rendering of a template ("[Semantical Error] The annotation "@Route" in method App\Controller\ItemsController::items() was never imported. Did you maybe forget to add a "use" statement for this annotation? in C:\Users\micha\Desktop\projekt pokazowy\symfony_4\config/routes\../../src/Controller/ (which is being imported from "C:\Users\micha\Desktop\projekt pokazowy\symfony_4\config/routes/annotations.yaml"). Make sure annotations are installed and enabled."). {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\config\\Loader\\FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:54, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\config\\Loader\\FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:54)"} []
[2018-04-29 18:55:54] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("[Semantical Error] The annotation "@Route" in method App\Controller\ItemsController::items() was never imported. Did you maybe forget to add a "use" statement for this annotation? in C:\Users\micha\Desktop\projekt pokazowy\symfony_4\config/routes\../../src/Controller/ (which is being imported from "C:\Users\micha\Desktop\projekt pokazowy\symfony_4\config/routes/annotations.yaml"). Make sure annotations are installed and enabled.")." at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\config\\Loader\\FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:54, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\config\\Loader\\FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:54)"} []
[2018-04-29 18:55:54] request.CRITICAL: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("[Semantical Error] The annotation "@Route" in method App\Controller\ItemsController::items() was never imported. Did you maybe forget to add a "use" statement for this annotation? in C:\Users\micha\Desktop\projekt pokazowy\symfony_4\config/routes\../../src/Controller/ (which is being imported from "C:\Users\micha\Desktop\projekt pokazowy\symfony_4\config/routes/annotations.yaml"). Make sure annotations are installed and enabled."). at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\twig-bundle\Resources\views\Exception\trace.html.twig line 13) {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"[Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes/annotations.yaml\"). Make sure annotations are installed and enabled.\"). at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\twig-bundle\\Resources\\views\\Exception\\trace.html.twig:13, Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\config\\Loader\\FileLoader.php:168, Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\ItemsController::items() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:54)"} []
[2018-04-29 18:56:09] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:56:09] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:56:09] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-29 18:56:09] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"3dbc69","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/3dbc69","method":"GET"} []
[2018-04-29 18:56:26] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:56:26] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:58:16] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:58:16] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:58:16] request.CRITICAL: Uncaught PHP Exception ErrorException: "Notice: Undefined variable: connection" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\src\Controller\ItemsController.php line 17 {"exception":"[object] (ErrorException(code: 0): Notice: Undefined variable: connection at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\src\\Controller\\ItemsController.php:17)"} []
[2018-04-29 18:58:16] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"87feb6","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/87feb6","method":"GET"} []
[2018-04-29 18:58:54] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:58:54] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:58:54] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 18:58:54] php.CRITICAL: Call to undefined function App\Controller\Response() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function App\\Controller\\Response() at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\src\\Controller\\ItemsController.php:18)"} []
[2018-04-29 18:58:54] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedFunctionException: "Attempted to call function "Response" from namespace "App\Controller"." at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\src\Controller\ItemsController.php line 18 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedFunctionException(code: 0): Attempted to call function \"Response\" from namespace \"App\\Controller\". at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\src\\Controller\\ItemsController.php:18)"} []
[2018-04-29 18:58:54] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"a95e42","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/a95e42","method":"GET"} []
[2018-04-29 18:59:20] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 18:59:20] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 18:59:20] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:12:29] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:12:29] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:12:30] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:12:31] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:12:31] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:12:31] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:12:58] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:12:58] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:12:58] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:13:38] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:13:38] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:13:38] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:13:40] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:13:40] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:13:40] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:15:10] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:15:10] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:15:10] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:15:17] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:15:17] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:15:17] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:15:17] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-29 20:15:47] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:15:47] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:15:47] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:16:00] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:16:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:16:00] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:16:00] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-29 20:16:43] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:16:43] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:16:43] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:16:43] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-29 20:16:57] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:16:57] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:16:57] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:17:22] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:17:22] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:17:22] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:17:22] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-29 20:17:36] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:17:36] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:17:36] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:17:36] request.CRITICAL: Uncaught PHP Exception ErrorException: "Notice: Undefined variable: request" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\src\Controller\ItemsController.php line 20 {"exception":"[object] (ErrorException(code: 0): Notice: Undefined variable: request at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\src\\Controller\\ItemsController.php:20)"} []
[2018-04-29 20:17:37] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"1f44f2","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/1f44f2","method":"GET"} []
[2018-04-29 20:17:49] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:17:49] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:17:49] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:17:49] php.CRITICAL: Type error: Argument 1 passed to Symfony\Component\HttpFoundation\Response::prepare() must be an instance of Symfony\Component\HttpFoundation\Request, array given, called in C:\Users\micha\Desktop\projekt pokazowy\symfony_4\src\Controller\ItemsController.php on line 20 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Symfony\\Component\\HttpFoundation\\Response::prepare() must be an instance of Symfony\\Component\\HttpFoundation\\Request, array given, called in C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\src\\Controller\\ItemsController.php on line 20 at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-foundation\\Response.php:256)"} []
[2018-04-29 20:17:49] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Symfony\Component\HttpFoundation\Response::prepare() must be an instance of Symfony\Component\HttpFoundation\Request, array given, called in C:\Users\micha\Desktop\projekt pokazowy\symfony_4\src\Controller\ItemsController.php on line 20" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-foundation\Response.php line 256 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Symfony\\Component\\HttpFoundation\\Response::prepare() must be an instance of Symfony\\Component\\HttpFoundation\\Request, array given, called in C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\src\\Controller\\ItemsController.php on line 20 at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-foundation\\Response.php:256)"} []
[2018-04-29 20:17:50] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"59cef0","_route":"_wdt"},"request_uri":"http://127.0.0.1:8000/_wdt/59cef0","method":"GET"} []
[2018-04-29 20:18:02] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:18:02] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:18:02] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:18:02] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-29 20:18:20] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:18:20] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:18:20] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:18:20] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-29 20:18:28] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:18:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:18:28] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:18:28] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-29 20:19:49] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:19:49] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:19:49] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:19:49] request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\HttpKernel.php line 165 {"exception":"[object] (LogicException(code: 0): The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller? at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\HttpKernel.php:165)"} []
[2018-04-29 20:20:08] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:20:08] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:20:08] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:22:16] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:22:16] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:22:16] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:22:17] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:22:17] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:22:17] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:26:35] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:26:35] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:26:35] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:27:54] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:27:54] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:27:54] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:28:28] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:28:28] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:28:28] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:28:29] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:28:29] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:28:29] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:28:45] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://127.0.0.1:8000/items","method":"GET"} []
[2018-04-29 20:28:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:28:45] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:29:46] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 20:29:46] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 20:29:46] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 20:29:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://localhost:8000/items")" at C:\Users\micha\Desktop\projekt pokazowy\symfony_4\vendor\symfony\http-kernel\EventListener\RouterListener.php line 144 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:8000/items\") at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:144, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\Users\\micha\\Desktop\\projekt pokazowy\\symfony_4\\var\\cache\\dev\\srcDevDebugProjectContainerUrlMatcher.php:119)"} []
[2018-04-29 22:13:08] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:13:08] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:13:09] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:13:22] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:13:22] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:13:22] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:14:02] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:14:02] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:14:02] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:14:26] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:14:26] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:14:26] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:15:04] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:15:04] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:15:04] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:15:35] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:15:35] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:15:35] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:17:18] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:17:18] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:17:18] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:17:34] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:17:34] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:17:34] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:17:48] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:17:48] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:17:48] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:18:41] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:18:41] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:18:41] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:19:15] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:19:15] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:19:16] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:21:26] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:21:27] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:21:28] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:22:40] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:22:40] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:22:40] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:22:59] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:22:59] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:22:59] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:23:25] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:23:25] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:23:25] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:23:38] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:23:38] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:23:38] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:24:22] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:24:22] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:24:23] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:25:46] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:25:46] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:25:46] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:25:50] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:25:50] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:25:50] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:26:05] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:26:05] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:26:05] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:27:35] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:27:35] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:27:35] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:28:54] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:28:54] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:28:54] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:28:57] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:28:57] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:28:57] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:29:00] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:29:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:29:01] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:29:16] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:29:16] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:29:16] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:29:34] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:29:34] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:29:34] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:33:51] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:33:51] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:33:51] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:34:08] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:34:08] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:34:08] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:34:29] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:34:29] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:34:29] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:34:43] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:34:43] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:34:43] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:35:29] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:35:29] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:35:29] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:36:09] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:36:09] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:36:09] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:38:35] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:38:35] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:38:35] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:38:50] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:38:50] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:38:51] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:39:46] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"OPTIONS"} []
[2018-04-29 22:39:46] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:39:46] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:41:11] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:41:11] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:41:11] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:41:33] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:41:33] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:41:33] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:41:39] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:41:39] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:41:39] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:41:52] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:41:52] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:41:52] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:42:06] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:42:06] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:42:06] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:42:32] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:42:32] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:42:32] doctrine.DEBUG: SELECT * FROM users [] []
[2018-04-29 22:42:45] request.INFO: Matched route "app_items_items". {"route":"app_items_items","route_parameters":{"_controller":"App\\Controller\\ItemsController::items","_route":"app_items_items"},"request_uri":"http://localhost:8000/items","method":"GET"} []
[2018-04-29 22:42:45] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2018-04-29 22:42:45] doctrine.DEBUG: SELECT * FROM users [] []
